# Use this file for an arm64 k8s cluster
kube-state-metrics:
  tolerations:
    - key: 'kubernetes.io/arch'
      value: 'arm64'
      operator: 'Equal'
      effect: 'NoSchedule'
container-optimization-data-forwarder:
  tolerations:
    - key: 'kubernetes.io/arch'
      value: 'arm64'
      operator: 'Equal'
      effect: 'NoSchedule'
