apiVersion: v2
description: Kubex Collection Stack
name: kubex-automation-stack
version: 1.0.1
type: application
icon: https://www.kubex.ai/wp-content/uploads/kubex-by-densify-logo.png
dependencies:
  - name: container-optimization-data-forwarder
    version: "4.*.*"
    repository: https://densify-dev.github.io/helm-charts
  - name: prometheus
    version: "27.*.*"
    repository: https://prometheus-community.github.io/helm-charts
keywords:
- kubex
- densify
- container
- optimization
maintainers:
- email: support@kubex.ai
  name: support
details:
  This Helm chart provides the entire stack required for container data collection and optimization
