apiVersion: v2
description: Densify Container Optimization Data Forwarder Utility
icon: https://www.densify.com/wp-content/uploads/densify.png
keywords:
- densify
- container
- optimization
maintainers:
- email: support@densify.com
  name: support
name: container-optimization-data-forwarder
type: application
version: 4.0.14
