apiVersion: v2
description: Kubex Data Collector for Container Optimization
icon: https://www.kubex.ai/wp-content/uploads/kubex-by-densify-logo.png
keywords:
- kubex
- densify
- container
- optimization
maintainers:
- email: support@kubex.ai
  name: support
name: container-optimization-data-forwarder
type: application
version: 4.0.13
