{{- if and .Values.openshift.enabled .Values.openshift.scc.createRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubex-automation-anyuid
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:{{ .Values.openshift.scc.name }}
subjects:
  {{- range .Values.openshift.scc.serviceAccounts }}
  - kind: ServiceAccount
    name: {{ . | quote }}
    namespace: {{ $.Release.Namespace }}
  {{- end }}
{{- end }}
