{{- if and .Values.createSecrets (not .Values.certmanager.enabled) .Values.selfSignedCert.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kubex-automation-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
{{ include "kubex-automation-controller.gen-certs" . | indent 2 }}
{{- end }}
