{{- if .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values.valkey.metrics.exporter.extraExporterEnvSecrets 0 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # Used by the redis exporter, automation controller and webhook to connect to Valkey
  REDIS_USER: {{ include "kubex-automation-controller.valkeyUsername" . | quote }}
  REDIS_PASSWORD: {{ include "kubex-automation-controller.valkeyPassword" . | quote }}
{{- end }}
