{{- if .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.valkey.extraSecretValkeyConfigs }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # These lines are appended to valkey.conf
  # Disable the default user and enable a named user with a password.
  # Quote password if they contain special characters. Password may not contain spaces.
  auth.conf: |
    user default off
    user {{ include "kubex-automation-controller.valkeyUsername" . }} on >'{{ include "kubex-automation-controller.valkeyPassword" . }}' +@all ~*
{{- end }}
