# Use this file for an arm64 k8s cluster
tolerations:
  - key: 'kubernetes.io/arch'
    value: 'arm64'
    operator: 'Equal'
    effect: 'NoSchedule'
webhook:
  tolerations:
    - key: 'kubernetes.io/arch'
      value: 'arm64'
      operator: 'Equal'
      effect: 'NoSchedule'
cainjector:
  tolerations:
    - key: 'kubernetes.io/arch'
      value: 'arm64'
      operator: 'Equal'
      effect: 'NoSchedule'
startupapicheck:
  tolerations:
    - key: 'kubernetes.io/arch'
      value: 'arm64'
      operator: 'Equal'
      effect: 'NoSchedule'
