apiVersion: v2
name: kubex-automation-controller
description: A Helm chart for deploying Kubex Automation Controller
type: application
version: 1.0.12
icon: https://www.kubex.ai/wp-content/uploads/kubex-by-densify-logo.png
dependencies:
  - name: valkey
    version: "2.*.*"
    repository: https://groundhog2k.github.io/helm-charts
maintainers:
- email: support@kubex.ai
  name: support
