# Use this file for an arm64 k8s cluster
valkey:
  tolerations:
    - key: 'kubernetes.io/arch'
      value: 'arm64'
      operator: 'Equal'
      effect: 'NoSchedule'
deployment:
  controller:
    tolerations:
      - key: 'kubernetes.io/arch'
        value: 'arm64'
        operator: 'Equal'
        effect: 'NoSchedule'
  webhook:
    tolerations:
      - key: 'kubernetes.io/arch'
        value: 'arm64'
        operator: 'Equal'
        effect: 'NoSchedule'
