{{- if and (not (.Values.stack.runsInGKEAutopilot)) (.Values.stack.gcpServiceAccountKeyName) (.Values.stack.gcpServiceAccountKeyContents) }}
apiVersion : v1
kind : Secret
metadata :
  name : gcp-service-account-secret
  namespace: {{ template "common.namespace" . }}
type : Opaque
data : 
  {{ .Values.stack.gcpServiceAccountKeyName }} : {{ .Values.stack.gcpServiceAccountKeyContents | b64enc | quote }}
{{- end }}
